"""empty message

Revision ID: f3c0c9df2045
Revises: 91816e99012e
Create Date: 2023-01-12 20:36:39.891219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import engine_from_config
from sqlalchemy.engine import reflection

config = op.get_context().config
engine = engine_from_config(
    config.get_section(config.config_ini_section), prefix="sqlalchemy."
)
inspector = reflection.Inspector.from_engine(engine)
columns = inspector.get_columns("items")

# revision identifiers, used by Alembic.
revision = 'f3c0c9df2045'
down_revision = '91816e99012e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not any([c['name'] == 'description' for c in columns]):
        with op.batch_alter_table('items', schema=None) as batch_op:
            batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
